### PR TITLE
Upgrade to angulillos 0.9.x

### PR DESCRIPTION
**Pull request by eparejatobes**
This will lead to significant simplifications here.

### CODE REVIEW

**Comment by eparejatobes** [comment]
> Do you have any code to show already?

just pushed. As this is going to be an uber-PR, I've deleted most of the old sources, and I will be adding graphs one by one.

**Comment by laughedelic** [comment]
I personally prefer excluding sources from compilation while working on such uber-PRs, this way you can replace code file-by-file keeping diff minimal.

**Comment by eparejatobes** [comment]
> I personally prefer excluding sources from compilation while working on such uber-PRs, this way you can replace code file-by-file keeping diff minimal.

Fine with it, but how? don't know the appropriate sbt incantation

**Comment by laughedelic** [comment]
We use it angulillos for [example](https://github.com/bio4j/angulillos/blob/master/build.sbt#L10-L12):

```scala
excludeFilter in unmanagedSources :=
  (excludeFilter in unmanagedSources).value ||
  // any glob-patterns here
```

**Comment by laughedelic** [comment]
FYI, you can check what's left after those filters with `show unmanagedSources` in the sbt console

**Comment by eparejatobes** [comment]
We need to do a thorough review of all graphs, and I don't want this to be mixed with updating to angulillos 0.9.x. I am merging this then, and then working on each graph in separate PRs.

**Comment by eparejatobes** [comment]
LGTM

**Pull request merged**
