### PR TITLE
Generic code for database cross-references

### PR DESCRIPTION
**Pull request by eparejatobes**
Interfaces for a graph which only adds an edge between vertices of two different graphs.

### CODE REVIEW

**Comment by eparejatobes** [comment]
Waiting for #72

**Comment by laughedelic** [comment]
You mean https://github.com/bio4j/bio4j/issues/124

**Comment by eparejatobes** [comment]
@laughedelic see https://github.com/bio4j/bio4j/pull/150#issuecomment-249599072

**Comment by laughedelic** [comment]
OK

**Comment by laughedelic** [comment]
So as far as I understand, after #150 there's not much left to do here:
- [ ] move `LInkGraph` to angulillos
- [ ] add init-blocks

Any thing else?

**Comment by laughedelic** [comment]
I updated angulillos here, and removed both old cross-reference code and the `LinkGraph` (which is now fused with the `TypedGraph`)

**Comment by eparejatobes** [comment]
Fine, I already updated everything else. LGTM.

**Pull request merged**
