### PR TITLE
Review GO graph

### PR DESCRIPTION
**Pull request by eparejatobes**
- [x] vertices, edges, properties
- [x] documentation

### CODE REVIEW

**Comment by eparejatobes** [comment]
About relationships and properties in this graph:

1. I think that the three subontologies should simply be a property, not a relationship (given our constant issues with supernodes everywhere)
2. Drop [GO slims](http://geneontology.org/page/go-slim-and-subset-guide)

**Comment by marina-manrique** [comment]
> I think that the three subontologies should simply be a property, not a relationship (given our constant issues with supernodes everywhere) 9b5e816

Ok

> Drop GO slims 62b29a5

Ok for now but I guess we'd like to have something similar to GO Slim eventually (cc @rtobes)

**Comment by rtobes** [comment]
> I think that the three subontologies should simply be a property, not a relationship (given our constant issues with supernodes everywhere) 9b5e816

Given that only the terms belonging to the same subontology are connected with a relationship I think that to have the type of ontology as a property is not a problem because the in the graphs of GO terms there are 3 subgraphs corresponding to the 3 different subontologies

> Drop GO slims 62b29a5
To obtain the GO Slim frequency of a GO term it is only needed to obtain the frequencies of all the connected terms (not being ancestors of that GO term). The most common operation will be to know the frequency of a term. Based on that and in the structure of the GO term DAG we can calculate the frequency of ancestors (LCA) and descendants (GO Slim).
I think that in many cases the LCA could be most interesting that the GO Slim because the LCA depends of the GO terms detected in the sample, and it is not aprioristically defined as is the case in Go Slim calciulation in which the set of terms is defined previously independently of the analyzed sample.

**Comment by eparejatobes** [comment]
OK fine. LGTM

**Pull request merged**
