### PR TITLE
Review all data import processes

### PR DESCRIPTION
**Pull request by eparejatobes**
- [ ] logging should be protected final, *non*-static. write a method for initialization/configuration. See http://wiki.apache.org/commons/Logging/StaticLog
- [ ] stats should be a method
- [ ] constants should be in a static namespace, and imported statically
- [ ] remove args from import methods, use method parameters instead.
- [x] remove uniprot xml conf
- [ ] factor import processes into separate methods, whenever possible

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic what do you think about rewriting all if(something == null) etc to Optional? It is *really* tedious but it would reduce the number of lines by half.

**Comment by laughedelic** [comment]
@eparejatobes I wanna see examples. It depends on how it's used, if there is some sensible logging (which I doubt), then it's not worth it. If it's just a check to use the value, then yeah, let's do it :wink: : : : : : : : : : : : : : : :

**Comment by laughedelic** [comment]
I see "Files changes 259" and I'm afraid to open the diff to review what you've changed.. :cold_sweat:

**Comment by eparejatobes** [comment]
@laughedelic this mostly contains foramtting changes. I will finish with that and start doing the rest in separate branches

**Pull request merged**
