### PR TITLE
Review NCBI Taxonomy graph

### PR DESCRIPTION
**Pull request by eparejatobes**
- [x] Vertices, edges, properties
- [x] Documentation

### CODE REVIEW

**Comment by eparejatobes** [comment]
Dear assignees:

- [ ] @laughedelic check 7357985 and tell what you think about this. I think that assuming this does not cause difficulties at the import level (serialization etc) it would be quite useful to have it.
- [ ] @laughedelic order and structure of type declarations (like fields after classes etc). It's good to have a standard for this, even more so if we expect to generate this kind of code at some point.
- [ ] @rtobes @marina-manrique check the vertices, edges and properties here: the names are OK, you don't miss anything, the documentation is good enough, etc.

**Comment by laughedelic** [comment]
@eparejatobes my opinion on 73579854d134615c138aae9c9cffd11063d5256c:
- yes, it's doable and at least with Titan shouldn't cause much trouble
- I think that this will delay both the model structure review and the code writing and it's not worth it now. As you mention code generation, I think it's better to leave this enums-stuff for when we are going to generate them.

**Comment by eparejatobes** [comment]
@laughedelic https://github.com/bio4j/bio4j/pull/115#issuecomment-239713300 OK. I'm leaving enums for now, and we can re-evaluate this once we start with the import code review; if we are not using them, the possible values for these properties should be documented anyway.

**Comment by laughedelic** [comment]
> I'm leaving enums for now,

Reading this again and doubting: leaving them in code or leaving them for later (removing for now)?

**Comment by eparejatobes** [comment]
> Reading this again and doubting: leaving them in code or leaving them for later (removing for now)?

sorry, that was poorly phrased. I mean having code with enums, if only as documentation; see for example https://github.com/bio4j/bio4j/blob/0318fc161cde22f3e581bf60c6e0909d3fd14eda/src/main/java/com/bio4j/model/go/GOGraph.java#L88-L93

**Comment by laughedelic** [comment]
> @laughedelic order and structure of type declarations

Done in b5e7b0c81a4f96b57e3b5fa7004e1da537fb21fa. Here's what I propose. For a vertex `Foo`:

```java
public final class Foo extends Vertex<Foo> {

  private Foo(V vertex) { super(vertex, foo); }
  @Override public final Foo self() { return this; }
}

public final FooType foo = new FooType();
public final class FooType extends VertexType<Foo> {

  @Override public final Foo fromRaw(V vertex) { return new Foo(vertex); }

  // Foo's properties...
}
```

Same for edges and properties. The only difference is that the type-type has a constructor declaration in addition to `fromRaw`.

- The value-type goes first because it has a fixed structure: its constructor and the self-reference, while the type-type can have multiple properties inside and its declaration may span across many lines so that when you view it or write, the value-type thing gets out of the visible scope
- Same reason for putting `FooType foo` value declaration right in front of the `FooType`
- Same reason for putting `Foo fromRaw` before properties
- `@Override` on the same line as the method, because these lines are pure boilerplate that is not useful when you are reading the code. So this way they occupy less space and don't distract you attention too much

An idea about indexes: we could put it inside of the property, like this:

```java
public final Id id = new Id();
public final class Id extends Property<String> implements FromAtMostOne, ToOne {

  private Id() { super(String.class); }

  /* A unique index for taxa by id */
  public final Index index = new Index();
  public final class Index extends UniqueIndex<Id, String> {

    private Index() { super(id); }
  }
}
```

@eparejatobes WDYT?

**Comment by eparejatobes** [comment]
Modulo https://github.com/bio4j/bio4j/pull/115#issuecomment-239628236 LGTM

**Comment by rtobes** [comment]
I have reviewed the comments of this code page:
- https://github.com/bio4j/bio4j/pull/115/files
I understand that the documentation consists in the comments included in the code. (Please tell me if there is another kind of documentation and where it is if it exists)

I have checked the vertex (only one type?), edges and properties.  The names are OK, I would like to have a figure with the model (I know that it is very simple but it is good to have it).
It is important to have the version of the taxonomy imported in the graph.

**Pull request merged**
