### PR TITLE
fix property types initialization

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@pablopareja take a look at this; I think we should do the same for all properties. Ultimately, this is what was causing issues in bio4j/bio4j-titan#61

**Comment by eparejatobes** [comment]
I think we should do the same with the other graphs

**Comment by pablopareja** [comment]
Ok, but what's the reason why the other graphs didn't throw any exception?

**Comment by eparejatobes** [comment]
After looking at this in more detail, for the sake of uniformity I'm doing the same as in the other graphs/modules. See for example

- https://github.com/bio4j/bio4j/blob/master/src/main/java/com/bio4j/model/uniprot/UniProtGraph.java#L1005-L1040

**Comment by eparejatobes** [comment]
I reviewed all the other graphs and everything was OK, so nothing to worry about. I just pushed essentially the same fix as before for UniRef, only that now it is done in the same way as in the other graphs.

Merging this, and releasing `0.12.RC1` so that we have something stable here.

**Pull request merged**
