### PR TITLE
UCSC human genome data integration

### PR DESCRIPTION
**Pull request by eparejatobes**
Human genome data coming to Bio4j! This issue/PR will serve for discussions and tracking progress.

cc @rtobes @marina-manrique

### CODE REVIEW

**Comment by evdokim** [comment]
I have already had experience with integration NCBI annotations to a graph database, and I think that we can do the same.

### vertices

* assemblies: hg19, hg38
* chromosomes: ch1, ch2, ... 

### edges

* from assembly to chromosome (different assembly shouldn't share chromosomes)
* from chromosome to Uniptot proteins vertices, one for each occurrence of the protein in the chromosome. Edge index for start position will do all job for querying genes by positions.
If we are going to work with more than one annotation then we also need property for annotation name.

**Comment by eparejatobes** [comment]
@evdokim during the next couple of days I'll think about what a good model for this requires, and which options do we have. I will also write something about it, in some format. 

You can do the same!

**Comment by eparejatobes** [comment]
Hey @evdokim the code you just pushed is basically copy-pasted from that of other graphs in bio4j/bio4j. There's 

- docs for something totally unrelated like NCBI taxonomy
- the author of most of it looks to be @pablopareja from what it's written there in the @author javadoc tag
- the code alignment is all wrong

Please fix all this.

**Comment by evdokim** [comment]
@eparejatobes done

**Comment by eparejatobes** [comment]
This is only a vertex type representing chromosomes. Am I missing something else?

**Comment by evdokim** [comment]
@eparejatobes I still have to add some properties + assembly vertices

**Comment by eparejatobes** [comment]
OK I'm waiting then for you to have your complete model here. Ping me once you're done! :+1:

**Comment by evdokim** [comment]
I will try to do it, but I do not promise that I will finish by Friday.

**Comment by evdokim** [comment]
@eparejatobes I added assemblies vertices and properties, basically now the code represents what I proposed: https://github.com/bio4j/bio4j/pull/93#issuecomment-75515446

**Comment by eparejatobes** [comment]
Fine @evdokim I will review this ASAP

**Comment by eparejatobes** [comment]
I will start first with chromosomes and assemblies. Chromosomes as entities should be completely decoupled from assemblies or anything like that; They should be types themselves linked with a _genome_, something that's also missing. There should also be a link to _some_ taxonomy module, which I would consider as a dependency.

Now a given assembly can have contigs linked with a chromosome, and we can work from there.

**Comment by eparejatobes** [comment]
@rtobes @marina-manrique I'd like you to be watching this, for the bio part. Thanks!

**Comment by marina-manrique** [comment]
:+1:

**Comment by evdokim** [comment]
@eparejatobes I agree on link to taxonomy, but I still don't understand what do you mean under genome?

Concerning chromosomes, probably it's a good idea, but are you sure that we want to deal with all that assembly specific things:

http://genome-euro.ucsc.edu/cgi-bin/hgTracks?hgsid=13085504&chromInfoPage=

**Comment by eparejatobes** [comment]
A genome can be thought of as an (ordered maybe?) set of chromosomes.

**Comment by rtobes** [comment]
Yes. 

The number of copies (haploid, diploid, tetraploid) of each chromosomes for each species could be important. X and Y chromosomes has only one copy in males that are XY. In females that are XX the Y chromosome does not exist. It is important for many things because the number of expected alelles for each gene in each individual genome depends on that.

**Comment by eparejatobes** [comment]
So in general I would define different chromosome _types_ per species (which would correspond to the usual numbers in humans); this way we can express all those XX/XY things and more generally (for other organisms) polyploidy-related concepts.

**Comment by rtobes** [comment]
OK.

**Comment by evdokim** [comment]
Let me explain my concern about chromosomes again: in theory we have fixed set of chromosome per species for human it will be chr1, ..., chr22, chrX, chrY and chrM for mitochondria. But when you start to talk about assemblies and annotations the picture there is not so ideal:
look again on the list of chromosomes that UCSC uses for their tracks: http://genome-euro.ucsc.edu/cgi-bin/hgTracks?hgsid=13085504&chromInfoPage=
I think that we should work with that chromosomes for UCSC Genes annotations because inside knownGenes they refer to them.
We still can introduce somewhere else (not in UCSCGenes module) abstract vertices that correspond to human chromosomes and then link them with UCSC chromosomes (when it's possible because they have some unplaced things like "chrUn_GL000195v1"). We can call that module "genomes" or something like that.

**Comment by evdokim** [comment]
Concerning contigs, I think that they should be vertices connected to UCSC chromosomes. Their positions stored in table "Gold", track "assembly" (you can see the schema in [the table browser](http://genome-euro.ucsc.edu/cgi-bin/hgTables?hgsid=202884322_wcHykibYW33C6CKYVKTj3jxuq37g&clade=mammal&org=Human&db=hg38&hgta_group=map&hgta_track=knownGene&hgta_table=0&hgta_regionType=genome&position=chr9%3A133252000-133280861&hgta_outputType=primaryTable&hgta_outFileName=)

**Comment by rtobes** [comment]
I think that we could have these types of chromosomes for human:
- chr1
- ....
- chr22
- chrX
- chrY
- chrM
- chrUn

The prefix previous to "_" character indicates the type of chromosome to which connect the different tracks ( http://genome-euro.ucsc.edu/cgi-bin/hgTracks?hgsid=13085504&chromInfoPage=).

If within each track there are contigs I think we would need to model tracks.

**Comment by evdokim** [comment]
@rtobes what do you mean exactly by types of chromosomes? That's something unrelated to UCSC right?

Didn't understand the tracks things. They called track all information that connected to genome coordinates: contigs, annotations etc

**Comment by eparejatobes** [comment]
Maybe it is a good idea to try to clarify the part about genomes, chromosomes and the like. We should keep in mind that this should be flexible and expressive enough so as to accomodate more general situations (plant genomics for example). As I wrote above, we should have chromosome types per species/strain/whatever; A genome type then would have (among other things) a particular configuration of chromosome types, essentially a sum of copies of chromosome types.

As a side note, all this _could_ be part of a different graph, but it would be anyway a dependency of what we are working on here.

@evdokim, replying below 

- about the "funny" chromosomes in UCSC data; some of them actually correspond to haplotypes, and thus from my point of view they are part of _different_ assemblies. This data _could_ be included but then it should correspond to a _different_ assembly. Some others, though, contain just crappy sequence and/or fragments that could not be scaffolded. In my opinion, they should be dropped.
- As you say each chromosome has several contigs, with different kind of gaps etc; this information is available and as far as I understand derived from the `.afg` files. And yes, each real contig (where real means composed of **contig**uos sequence) should be a vertex.

@rtobes do we really need that `chrUn` crap? If we really need to have that sequence I'd rather leave it there without any chromosome adscription than reinventing [`null`](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions).

**Comment by rtobes** [comment]
My idea is to model the types of chromosomes per species (as @eparejatobes said) and then within each type to have the sequences (tracks). For example the concrete sequences for chr1 and for chr1_GL383518v1_alt would be connected to chr1 chromosome type.

If within these sequences there is not any contig other possibility would be to call them as contigs. These are the sequences that I am referring:
-  http://genome-euro.ucsc.edu/cgi-bin/hgTracks?hgsid=13085504&chromInfoPage=

@evdokim, Are contigs within each of them?

**Comment by eparejatobes** [comment]
@rtobes there are, actually a lot of them. Check this for example: http://genome.ucsc.edu/goldenPath/datorg.html

**Comment by evdokim** [comment]
>My idea is to model the types of chromosomes per species (as @eparejatobes said) and then within each type to have the sequences (tracks). For example the concrete sequences for chr1 and for chr1_GL383518v1_alt would be connected to chr1 chromosome type.

I suggested the same

>@evdokim, Are contigs within each of them?

No, they have different table (table "Gold", track "assembly") with fragments that connected to the list of "funny" chromosomes. 

>about the "funny" chromosomes in UCSC data; some of them actually correspond to haplotypes, and thus from my point of view they are part of different assemblies. This data could be included but then it should correspond to a different assembly. Some others, though, contain just crappy sequence and/or fragments that could not be scaffolded. In my opinion, they should be dropped.

You suggest to introduce hundreds new assemblies?

>As you say each chromosome has several contigs, with different kind of gaps etc; this information is available and as far as I understand derived from the .afg files. And yes, each real contig (where real means composed of contiguos sequence) should be a vertex.
Can you explain that using UCSC terminology because I'm a bit lost

**Comment by eparejatobes** [comment]
The `.fa` files are **full** of contigs, just download one of them at random and open it. Unless you consider this a particularly interesti`n`g region of the human genome:

```
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```

**Comment by rtobes** [comment]
Sorry because I respond without refreshing the page and this appears a confusing dialog.

I think that it is better to model only the sequences defined as belonging to some specific type of chromosome avoiding chrUn sequences.

This is my opinion.

**Comment by rtobes** [comment]
Is this the directory that we are going to use to download the sequences?

- http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/

**Comment by evdokim** [comment]
let me summarize:

* we are going to drop all chrUn_* chromosomes
* we will have abstract "chr1", "chr2", ... , "chr22", "chrX", "chrY", "chrM"
* all UCSC chromosomes (except "chrUn_*") together with thir connection to abstract ones
* we want to put also contigs. But I still do not understand the point of @eparejatobes . UCSC have a [file](http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.agp.gz) with all fragments including contigs (use table browser to see its format). I think that we can just import all of them as vertices together with links to UCSC chromosomes (and drop those that refer to "chrUn_*")

**Comment by evdokim** [comment]
@rtobes Is this the directory that we are going to use to download the sequences?
http://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/

that directory contains sequences of all UCSC chromosomes. So we will need them in order to import sequence data.

**Comment by evdokim** [comment]
this is my draft for bio4j model. Probably it easy to understand that all comments above

#### genomes module
##### vertices

* genomes (properties: name)
* chromosomes (for human chr1, ..., chrX, chrY, chrM) (properties: name, "ploidy")

##### edges

* genome to chromosome 

#### genomesNCBITaxonomy module
##### edges

* genome to taxon

#### UCSC module (now it's called as UCSCGenes)
##### vertices

* assemblies (properties: name, version??)
* chromosomes (UCSC chromosomes including "chr1_sdsads" for example) (properties: name)
* fragments or contigs (properties: ids, type ((W)GS contig, (P)redraft, (D)raft, (F)inished or (O)ther))

##### edges

* assembly to chromosomes
* chromosomes to fragments ("assembly" / "gold" table) (properties: positions, orientation)

#### UCSCGenomes module
##### edges

* assembly to genome
* UCSC chromosome to chromosome

#### UCSCUniprot module
##### edges

* ucsc chromosome to protein (knownGenes table) (properties: positions, orientation)

**Comment by eparejatobes** [comment]
I think that we all agree (modulo details) on the model for chromosome types and genomes; we need code for this then.

Another thing that's missing here is a document containing links and descriptions for the raw data that will be used as input; we are already spending more time than ideal on making sure that we are all talking about the same data.

So let's have these two things first before continuing with the discussion:

- [ ] @evdokim code for the genomes and chromosomes part
- [ ] @evdokim a document containing links and descriptions for all the raw UCSC data

**Comment by evdokim** [comment]
>I think that we all agree (modulo details)

I do hope that we do

the first part (model + importing code) will be ready soon.

the second part is easy see [ucsc.md](https://github.com/bio4j/bio4j/blob/graph/human/genome/data/docs/human%20data/ucsc.md)

**Comment by eparejatobes** [comment]
About 478f4f55a7f6386770ae27663144da0ca7d10dbb: I wouldn't call that a document. @rtobes please review.

**Comment by eparejatobes** [comment]
@evdokim just in case it was not clear: the part that for me is (more or less) clear is genome and chromosome types; just that.

**Comment by evdokim** [comment]
@eparejatobes I suggest to make a meeting and discuss it then. Because I have no idea how to express myself more clearly.

**Comment by rtobes** [comment]
Copy paste is not a good manner to explain a work whose author should be you, and that should reflect your intelligence. Do the things with calm. If to communicate your ideas is difficult for you please work on it. We known that you are perfectly able to do that.

**Comment by evdokim** [comment]
@rtobes I tried to to explain in it using comments then using more formal description with schema. I thing that it would be much easy just to speak about it.

**Comment by rtobes** [comment]
It is a good idea to do an schema. Do that and also do a graph representation of it.

**Comment by eparejatobes** [comment]
@evdokim I will try to add more details to what we're waiting for here:

1. An implementation of the model for genomes and chromosome types
2. A document describing the raw data from UCSC that will be used as input for the import process. This should contain (among other things) a description of what they have there (both general and particular, as needed) together with links to where the data is.

**Comment by evdokim** [comment]
@rtobes graphical representation of schema? I just thought about it.

**Comment by evdokim** [comment]
>An implementation of the model for genomes and chromosome types

I'm doing it right now


> A document describing the raw data from UCSC that will be used as input for the import process. This should contain (among other things) a description of what they have there (both general and particular, as needed) together with links to where the data is.

I will mark ucsc.md the fields that we use in the graph. My idea in general is very simple: we use graphs instead tables, but we still can use the same fields as they are using.

**Comment by evdokim** [comment]
ok I've implemented the model (see last commit), some properties are still missing but the idea should be clear now.

**Comment by evdokim** [comment]
I changed format of [ucsc.md](https://github.com/bio4j/bio4j/blob/graph/human/genome/data/docs/human%20data/ucsc.md) now it's more readable. I also added correspondence from fields to edge properties.

**Comment by evdokim** [comment]
ping

**Comment by rtobes** [comment]
I think that in the table the example value for cdsEnd is 51,745.

To avoid confusion in the concepts (cdsStart and cdsEnd can not be identical positions) please review that all the data is correct in the table.

I think that here you can find the same knowGene example:
- http://varianttools.sourceforge.net/Annotation/KnownGene

**Comment by evdokim** [comment]
@rtobes sorry but I do not understand the problem. They have two numbers for every "alignment" for gene: `cdsStart` -- start position of coding region and `cdsEnd` -- end position of coding region. We do not have any way to control what they actually put there but we can expect that they are following their own schema.
Example in table, are just taken from the table browser and I think that they gave it just as illustration to show how values look like and apparently values for the examples do not correspond to a single row in the table "knownGenes".

**Comment by rtobes** [comment]
The reason why cdsStart and cdsEnd are the same position in that case is because this is a pseudogene and the transcript does not correspond to any CDS (Coding DNA Sequence).

I think that all the data in the example table corresponds to the actual uc001aaa.3  knowGene.

**Comment by evdokim** [comment]
>I think that all the data in the example table corresponds to the actual uc001aaa.3 knowGene.

you are right, I found that line in knownGenes:

```
uc001aaa.3      chr1    +       11873   14409   11873   11873   3       11873,12612,13220,      12227,12721,14409,              uc001aaa.3
```

**Comment by eparejatobes** [comment]
closing, will be done elsewhere.

**Pull request closed without merging**
