### PR TITLE
Review NCBI Taxonomy graph

### PR DESCRIPTION
**Pull request by eparejatobes**
- [x] Rank enum: establish a reasonable convention, deal with no-rank properly.
- [x] document the names properties
- [x] do we include GenBank divisions and categories *now*? NO

### CODE REVIEW

**Comment by eparejatobes** [comment]
LGTM

**Comment by rtobes** [comment]
I didn't know the infraclass rank.

**Comment by eparejatobes** [comment]
There's also

1. superfamily
2. infraorder
3. parvorder (WTF)
4. varietas
5. forma
6. subclass
7. superclass
8. ...

**Comment by eparejatobes** [comment]
As usual, nowhere documented. From Wikipedia

> There is an indeterminate number of ranks, as a taxonomist may invent a new rank at will, at any time, if they feel this is necessary.

**Comment by laughedelic** [comment]
:trollface:

**Pull request merged**
