### PR TITLE
Review Enzyme graph

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
After reading again http://enzyme.expasy.org/enzuser.txt it looks like what is now a property (PROSITE cross-references) should probably be either dropped or upgraded to a cross-reference (see #129)

**Comment by eparejatobes** [comment]
@bio4j/bio-people please confirm that we are dropping PROSITE cross-refs here; PROSITE itself is not open: http://prosite.expasy.org/prosite_license.html

**Comment by eparejatobes** [comment]
LGTM from me.

**Comment by rtobes** [comment]
@eparejatobes, 
The cross-references to PROSITE from ENZYME database are not very important because in any case we have the PROSITE cross-references of each Uniprot protein included in each enzyme entry. (I don´t know if this answer your question)

**Comment by marina-manrique** [comment]
@eparejatobes as we discussed yesterday it's fine to drop the prosite refs from EnzymeDB

**Pull request merged**
